### ISSUE TITLE
overlapping divs on personal page

### ISSUE THREAD

**Issue by spestana** [Mountain-Hydrology-Research-Group/MTNHYDR_website#2]
I noticed while editing my bio (divs "secondBar" and "bioDesc") that if I put enough text in there, the divs "thirdBar" and "tertiaryPicture" would start to overlap and block the text. These div classes are defined in Profile.css.

You can see the div overlapping on my page where I edited my bio https://github.com/spestana/MTNHYDR_website/blob/main/Pages/People%20Profiles/StevenPestana.html

**Comment by j-amma** [comment]
Related: I'm not sure if this is by mistake or design, but the hypotheses on the '[Forests and Snow](https://depts.washington.edu/mtnhydr/Pages/Research%20Profiles/forestsAndSnow.html)' page overflow into notablePubLinks class at the bottom of the page.

**Comment by spestana** [comment]
It looks like this has all been fixed with CSS changes. I'm going to close this issue!
